kind: Service
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: vortex
spec:
  selector:
    app: prometheus
  {{- if .Values.service.nodePort }}
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30003
  {{- else }}
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
  {{- end }}
