kind: Service
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: vortex
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090

---

{{- if .Values.service.nodePort }}
kind: Service
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: prometheus-external
  namespace: vortex
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30003
{{- end }}