{{- if .Values.secret.dockerToken }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.secret.dockerToken }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerhub-token
type: kubernetes.io/dockerconfigjson
{{- end }}