apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-storage 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /nfsshare 
    server: 10.14.1.100
  persistentVolumeReclaimPolicy: Recycle 