kind: Service
apiVersion: v1
metadata:
  name: vortex-server
  namespace: vortex
  labels:
    app: vortex-server
spec:
  selector:
    app: vortex-server
  ports:
    - name: apiserver
      protocol: TCP
      port: 7890
      targetPort: 7890
      nodePort: 32326
    - name: webapp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32767
  type: NodePort
