---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-manual
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: {{ .Values.global.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"