---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: vortex
  labels:
    name: influxdb
    service: influxdb
spec:
  selector:
    service: influxdb
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 8086 
    targetPort: 8086

---

{{- if .Values.service.nodePort }}

apiVersion: v1
kind: Service
metadata:
  labels:
    environment: testing
  name: influxdb-external
  namespace: vortex
spec:
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  selector:
    service: influxdb
  ports:
  - name: influxdb
    port: 8086
    nodePort: 32086
    targetPort: 8086
    protocol: TCP
  
{{- end }}