apps:
  vortex-server:
    controller:
      replicaCount: 1
    replicaCount: 1
    controller:
      apiserverImageTag: v0.1.7
      webappImageTag: 0.1.0
    service:
      ports:
        apiserverNodePort: 32326
        webappNodePort: 32767
  network-controller:
    controller:
      imageTag: v0.4.0
  prometheus:
    controller:
      replicaCount: 1
      imageTag: v2.2.1
      scrapeInterval: 5s
      retention: 1h
    service:
      nodePort: true
    # dependencies
    cadvisor:
      controller:
        imageTag: latest
        housekeeping_interval: 10s
    kube-state-metrics:
      controller:
        imageTag: v1.3.1
    node-exporter:
      controller:
        imageTag: 1.0.1

services:
  mongodb:
    controller:
      replicaCount: 1
      cpu: 100m
      image:
        tag: 4.1.1-xenial
      pvc:
        localVolume: true
        reclaimPolicy: Delete
        accessModes: ReadWriteOnce
        storageClass: mongo
        storage: 1Gi
    service:
      nodePort: true
      