---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: vortex
spec:
  selector:
    service: mongo
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017

---

{{- if .Values.service.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: mongo-external
  namespace: vortex
spec:
  selector:
    service: mongo
  type: NodePort
  ports:
  - port: 27017
    nodePort: 31717
    targetPort: 27017
    protocol: TCP
{{- end }}