apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: vortex
spec:
  serviceName: "mongo"
  replicas: {{ .Values.controller.replicaCount }}
  template:
    metadata:
      labels:
        service: mongo
        role: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          resources:
            requests:
              cpu: {{ .Values.controller.cpu }}
          image: mongo:{{ .Values.controller.image.tag }}
          command:
            - mongod
            - "--bind_ip"
            - 0.0.0.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ {{ .Values.controller.pvc.accessModes | quote }} ]
      storageClassName: {{ .Values.controller.pvc.storageClass }}
      resources:
        requests:
          storage: {{ .Values.controller.pvc.storage }}
