kind: Service
apiVersion: v1
metadata:
  name: vortex-server
  namespace: vortex
  labels:
    app: vortex-server
spec:
  type: NodePort
  ports:
    - name: apiserver
      protocol: TCP
      port: 7890
      targetPort: 7890
      nodePort: {{ .Values.service.ports.apiserverNodePort }}
    - name: webapp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.ports.webappNodePort }}
  selector:
    app: vortex-server
